---
title: "Indeed-R-Analysis"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, echo = FALSE, warning = FALSE)
```

## Libraries

```{r, echo=TRUE}
library(tidyverse)

library(ggplot2)

#install.packages("dplyr")
library(dplyr)

#install.packages("ggrepel")
library(ggrepel)

#install.packages("GGally")
library(GGally)

#install.packages("forcats")
library(forcats)

#install.pacakges("patchwork")
library(patchwork)

#install.packages("readr")
library(readr)  

#install.package("stringr")
library(stringr)

#install.package("usethis")
library(usethis)

#install.packages("tm")
library(tm)

#install.packages("SnowballC")
library(SnowballC)

#install.packages("wordcloud")
library(wordcloud)

#install.packages("RColorBrewer")
library(RColorBrewer)

```

## Read Files

```{r, echo=TRUE}


# 1. List of CSV files
csv_files <- list.files(pattern = "\\.csv$", full.names = TRUE)

# 2. Read CSV files and add a new column with the file name
combined_data <- NULL

for (csv_file in csv_files) {
  file_name <- tools::file_path_sans_ext(basename(csv_file))  # Extract file name without extension
  data <- read.csv(csv_file)
  data$source_file <- file_name  # Add a new column with the file name
  combined_data <- rbind(combined_data, data)
}

```

### Data Cleaning

Delimiting \@ and \# to create category, city and date

```{r, echo=TRUE}
combined_data <- transform(combined_data, 
                           category = gsub("@.*", "", source_file),
                           city = gsub(".*@|\\#.*", "", source_file),
                           date = gsub(".*\\#", "", source_file))
```

Salary calculation

```{r, echo=TRUE}

combined_data$Lower_Salary <- NA
combined_data$Upper_Salary <- NA

for (i in 1:nrow(combined_data)) {
  if (str_detect(combined_data$salary[i], "year")) {
  
    split <- as.numeric(gsub(",","",gsub("[^0-9,]", "", unlist(strsplit(combined_data$salary[i], " - ")))))
    
    combined_data$Lower_Salary[i] <- split[1]
    combined_data$Upper_Salary[i] <- split[2]
  }
  if (str_detect(combined_data$salary[i], "month")) {
  
    split <- as.numeric(gsub(",","",gsub("[^0-9,]", "", unlist(strsplit(combined_data$salary[i], " - ")))))
    
    combined_data$Lower_Salary[i] <- split[1]*12
    combined_data$Upper_Salary[i] <- split[2]*12
  }
  if (str_detect(combined_data$salary[i], "hour")) {
  
    split <- as.numeric(gsub(",","",gsub("[^0-9,]", "", unlist(strsplit(combined_data$salary[i], " - ")))))
    
    combined_data$Lower_Salary[i] <- split[1]*260*8
    combined_data$Upper_Salary[i] <- split[2]*260*8
  }
  
  combined_data$Upper_Salary[is.na(combined_data$Upper_Salary)] <- combined_data$Lower_Salary[is.na(combined_data$Upper_Salary)]
}

#create an average salary column
combined_data <- combined_data %>%
  mutate(Average_Salary = (Lower_Salary + Upper_Salary) / 2)

```

### Salary analysis comparing cities

Mean Salary by City

```{r, echo=TRUE}

summary_by_city <- combined_data %>%
  group_by(city) %>%
  summarize(
    Mean_Salary = mean(Average_Salary, na.rm = TRUE),
    Median_Salary = median(Average_Salary, na.rm = TRUE),
    Min_Salary = min(Average_Salary, na.rm = TRUE),
    Max_Salary = max(Average_Salary, na.rm = TRUE),
    Count = n()
  )

ggplot(summary_by_city, aes(x = city, y = Mean_Salary/1000)) +
  geom_bar(stat = "identity", fill = "orange") +
  labs(title = "Mean Salary by City", x = "City", y = "Mean Salary (thousands)")+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

Boxplots of Salary by City

```{r, echo=TRUE}

ggplot(combined_data, aes(x = city, y = Average_Salary/1000)) +
  geom_boxplot(fill = "orange", color = "black", outlier.shape = NA) +
  labs(title = "Boxplot of Salary by City", x = "City", y = "Salary (thousands)")+ 
  coord_cartesian(ylim = c(0, 300))+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r, echo=TRUE}

# Sample dataset of US cities with salary information
us_cities <- data.frame(
  city = c("austin", "chicago", "houston", "los_angeles", "new_york","dallas", "philadelphia", "phoenix", "san_antonio", "san_diego"),
  lon = c(-97.7431, -87.6298, -95.3698, -118.2437, -74.006,-96.797,-75.1652, -112.0740, -98.4946, -117.1611),
  lat = c(30.2672, 41.8781, 29.7604, 34.0522, 40.7128,32.7767, 39.9626, 33.4484, 29.4252,32.7157))

us_cities <- left_join(us_cities, summary_by_city, by = "city")

# Define color gradient
color_gradient <- scale_color_gradient(low = "red", high = "green")


# Create a map of US cities with color gradient based on salary income
ggplot() +

  geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group), fill = "lightgrey", color = "grey") +  
  geom_polygon(data = map_data("usa"), aes(x = long, y = lat, group = group), fill = NA, color = "black") +

  geom_point(data = us_cities, aes(x = lon, y = lat, color = Median_Salary), size = 3) +
  geom_text(data = us_cities, aes(x = lon, y = lat, label = city), hjust = 0.7, vjust = 0, size = 2, color="black",family = "Arial") + # Add city labels
  labs(title = "US Cities Map with Salary Income") +
  color_gradient +
  theme_void()

```

### Job Titles and Salary

```{r,echo=TRUE}

ggplot(combined_data, aes(x = category, y = Average_Salary/1000)) +
  geom_boxplot(fill = "darkgreen", color = "black", outlier.shape = NA) +
  labs(title = "Boxplot of Salary by Job Title", x = "Job Title", y = "Mean Average Salary (thousands)")+ 
  coord_cartesian(ylim = c(0, 300))+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Remote, Hybrid and In-person Work

```{r, echo=TRUE}
# Search for "remote" and "hybrid" in job_description column
combined_data$work_type <- ifelse(grepl("remote", combined_data$job_description, ignore.case = TRUE), "Remote",ifelse(grepl("hybrid", combined_data$job_description, ignore.case = TRUE), "Hybrid", "In-Person"))

# Count the frequency of each work type
work_type_counts <- table(combined_data$work_type,combined_data$category)

# Convert to data frame
work_type_df <- as.data.frame(work_type_counts)

data_analyst <- subset(work_type_df, Var2 == "data_analyst")
data_engineer <- subset(work_type_df, Var2 == "data_engineer")
data_scientist <- subset(work_type_df, Var2 == "data_scientist")

# Function to create pie chart
create_pie_chart <- function(data, title) {
  pie_chart <- ggplot(data, aes(x = "", y = Freq, fill = Var1)) +
    geom_bar(stat = "identity", width = 1) +
    coord_polar("y", start = 0) +
    labs(title = paste("Proportion of Job Types for", title), fill = "Job Type", y = NULL) +
    theme_void() +
    scale_fill_manual(values = c("Remote" = "aquamarine", "Hybrid" = "cyan", "In-Person" = "blue"))
  print(pie_chart)
}

# Create pie charts for each job title
create_pie_chart(data_analyst, "Data Analyst")
create_pie_chart(data_engineer, "Data Engineer")
create_pie_chart(data_scientist, "Data Scientist")
```

### Work Type and Salary

```{r, echo=TRUE}

# Exclude NAs and empty values
combined_data_omit <- na.omit(combined_data)

# Create box plots
box_plot <- ggplot(combined_data_omit, aes(x = work_type, y = Average_Salary/1000, fill = work_type)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width=0.1) +
  labs(title = "Salary by Job Title and Work Type", x = "Job Title", y = "Salary in thousands", fill = "Work Type") +
  scale_fill_manual(values = c("Remote" = "aquamarine", "Hybrid" = "cyan", "In-Person" = "blue")) +
  coord_cartesian(ylim = c(0, 300))+ 
  theme_minimal() +
  facet_wrap(~category)

# Print the box plots
print(box_plot)

```
### Job Description

```{r, echo=TRUE}
# Filter for rows where category contains "data_analyst"
analyst_df <- combined_data %>%
  filter(str_detect(category, "data_analyst"))

analyst_text <- paste(analyst_df$job_description, collapse = " ")


# Filter for rows where category contains "data_scientist"
scientist_df <- combined_data %>%
  filter(str_detect(category, "data_scientist"))

scientist_text <- paste(scientist_df$job_description, collapse = " ")


# Filter for rows where category contains "data_engineer"
engineer_df <- combined_data %>%
  filter(str_detect(category, "data_engineer"))

engineer_text <- paste(engineer_df$job_description, collapse = " ")


# Create corpra for each category
```

### Cleaning 
```{r, echo=TRUE}

analyst_docs <- Corpus(VectorSource(analyst_text))

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))

analyst_docs <- tm_map(analyst_docs, toSpace, "/")
analyst_docs <- tm_map(analyst_docs, toSpace, "@")
analyst_docs <- tm_map(analyst_docs, toSpace, "\\|")
analyst_docs <- tm_map(analyst_docs, toSpace, "\n")

# Convert the text to lower case
analyst_docs <- tm_map(analyst_docs, content_transformer(tolower))
# Remove numbers
analyst_docs <- tm_map(analyst_docs, removeNumbers)
# Remove english common stopwords
analyst_docs <- tm_map(analyst_docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
analyst_docs <- tm_map(analyst_docs, removeWords, c("will", "job", "years", "working", "related")) 
# Remove punctuations
analyst_docs <- tm_map(analyst_docs, removePunctuation)
# Eliminate extra white spaces
analyst_docs <- tm_map(analyst_docs, stripWhitespace)
# Text stemming
#analyst_docs <- tm_map(analyst_docs, stemDocument)
```
```{r,echo=TRUE}

dtm <- TermDocumentMatrix(analyst_docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 30)

```
```{r,echo=TRUE}

set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1000,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(5, "Dark2"))
```

http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know